service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs12.x

functions:
  pageViewBot:
    handler: index.handler
    name: page-view-bot
    description: Runs through faith4.net posts once
    memorySize: 1600
    timeout: 600
