service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs12.x

functions:
  pageViewBot:
    handler: index.handler
    name: page-view-bot
    description: Runs through faith4.net posts once
    memorySize: 1600
    timeout: 600
    events:
      - schedule:
          rate: cron(0 8 * * ? *)
          input:
            page: 1
      - schedule:
          rate: cron(0 9 * * ? *)
          input:
            page: 2
      - schedule:
          rate: cron(0 10 * * ? *)
          input:
            page: 3
      - schedule:
          rate: cron(0 11 * * ? *)
          input:
            page: 4
      - schedule:
          rate: cron(0 12 * * ? *)
          input:
            page: 5
      - schedule:
          rate: cron(0 13 * * ? *)
          input:
            page: 6
      - schedule:
          rate: cron(0 14 * * ? *)
          input:
            page: 7
      - schedule:
          rate: cron(0 15 * * ? *)
          input:
            page: 8
      - schedule:
          rate: cron(0 16 * * ? *)
          input:
            page: 9
      - schedule:
          rate: cron(0 17 * * ? *)
          input:
            page: 10
      - schedule:
          rate: cron(0 18 * * ? *)
          input:
            page: 11
      - schedule:
          rate: cron(0 19 * * ? *)
          input:
            page: 12
      - schedule:
          rate: cron(0 20 * * ? *)
          input:
            page: 13
      - schedule:
          rate: cron(0 21 * * ? *)
          input:
            page: 14
      - schedule:
          rate: cron(0 22 * * ? *)
          input:
            page: 15
      - schedule:
          rate: cron(0 23 * * ? *)
          input:
            page: 16

